PRAGMA foreign_keys = ON;
CREATE TABLE users (id TEXT PRIMARY KEY, external_id TEXT NOT NULL UNIQUE, email TEXT NOT NULL, display_name TEXT NOT NULL, availability TEXT NOT NULL DEFAULT 'offline' CHECK (availability IN ('available','busy','offline')), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE contacts (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), name TEXT NOT NULL, phone_e164 TEXT NOT NULL, phone_original_encrypted TEXT, source TEXT NOT NULL, do_not_call INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE consents (id TEXT PRIMARY KEY, contact_id TEXT NOT NULL REFERENCES contacts(id), legal_basis TEXT NOT NULL, source TEXT NOT NULL, captured_at INTEGER NOT NULL, expires_at INTEGER, evidence_encrypted TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE campaigns (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), name TEXT NOT NULL, status TEXT NOT NULL CHECK (status IN ('draft','running','paused','stopped','completed')), concurrency INTEGER NOT NULL DEFAULT 3 CHECK (concurrency BETWEEN 1 AND 10), idempotency_key TEXT NOT NULL UNIQUE, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE dial_rounds (id TEXT PRIMARY KEY, campaign_id TEXT NOT NULL REFERENCES campaigns(id), status TEXT NOT NULL CHECK (status IN ('starting','dialing','winner_locked','completed','cancelled')), winner_attempt_id TEXT, idempotency_key TEXT NOT NULL UNIQUE, started_at INTEGER NOT NULL, completed_at INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE call_attempts (id TEXT PRIMARY KEY, round_id TEXT NOT NULL REFERENCES dial_rounds(id), contact_id TEXT NOT NULL REFERENCES contacts(id), provider TEXT NOT NULL, provider_call_id TEXT, status TEXT NOT NULL, classification TEXT, error_code TEXT, version INTEGER NOT NULL DEFAULT 0, started_at INTEGER, answered_at INTEGER, connected_at INTEGER, ended_at INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE provider_events (id TEXT PRIMARY KEY, provider TEXT NOT NULL, external_event_id TEXT NOT NULL, attempt_id TEXT REFERENCES call_attempts(id), event_type TEXT NOT NULL, payload_hash TEXT NOT NULL, occurred_at INTEGER NOT NULL, received_at INTEGER NOT NULL, processed_at INTEGER);
CREATE TABLE call_results (id TEXT PRIMARY KEY, attempt_id TEXT NOT NULL UNIQUE REFERENCES call_attempts(id), owner_id TEXT NOT NULL REFERENCES users(id), outcome TEXT NOT NULL CHECK (outcome IN ('interested','callback','sale','not_interested','invalid_number')), notes_encrypted TEXT, do_not_call INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE blocklist (id TEXT PRIMARY KEY, phone_hash TEXT NOT NULL UNIQUE, reason TEXT NOT NULL, source TEXT NOT NULL, blocked_at INTEGER NOT NULL, expires_at INTEGER);
CREATE TABLE audit_logs (id TEXT PRIMARY KEY, actor_id TEXT, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, correlation_id TEXT NOT NULL, metadata_redacted TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE rate_limits (key TEXT PRIMARY KEY, window_started_at INTEGER NOT NULL, count INTEGER NOT NULL);
CREATE INDEX idx_contacts_owner_phone ON contacts(owner_id, phone_e164);
CREATE INDEX idx_rounds_campaign_status ON dial_rounds(campaign_id, status);
CREATE INDEX idx_attempts_round_status ON call_attempts(round_id, status);
CREATE UNIQUE INDEX uq_attempts_provider_call ON call_attempts(provider, provider_call_id) WHERE provider_call_id IS NOT NULL;
CREATE UNIQUE INDEX uq_provider_events_external ON provider_events(provider, external_event_id);
CREATE INDEX idx_audit_entity_created ON audit_logs(entity_type, entity_id, created_at);
PRAGMA optimize;
